service:
  name: basic

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x

package:
  individually: true

functions:

  hello:
    handler: hello.handler
    events:
      - http:
          path: /hello
          method: get
          authorizer:
            name: authorizer
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: request

  authorizer:
    handler: authorizer.handler


resources:
  Resources:
    
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.WWW-Authenticate: "'Basic'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
